project:
  type: website

website:
  title: "Logan Bright's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sample_analysis.qmd
      - href: L_Bright_Resume.pdf
        text: Resume
        target: _blank
      - href: L_Bright_Cover_Letter.pdf
        text: Cover Letter
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link_external-newwindow: true