project:
  type: website

website:
  title: "my-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: L_Bright_Resume_St_Lukes_Data_Engineer_April_2026.pdf
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



